language: node_js
node_js:
  - "7.2"
cache: yarn
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
script:
  - npm run lint
  - npm run cover
